including: incl
population: pop
total: tot
american: amer
alaska: ak
tribal: tribe
groupings: grp
three: 3
two: 2
one : 1
four: 4
five: 5
six: 6
excluding: excl
other: othr
nativity: brth
citizenship: ctznshp
status: stat
black: blk
african: afro
citizen: ctzn
naturalized: nat
foreign: fgn
united: u
states: s
hawaiian: hi
other: othr
pacific: pacif
islander: isl
hispanic: hisp
latino: lat
over: ovr
year: yr
birth: brth
central: cntrl
america: amer
families: fams
subfamilies: subfams
number: nmbr
children: kids
income: incm
poverty: pvrty
level: lvl
under: undr
